aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - shadowenv
    - neofetch
    - ripgrep
    - curl
    - unzip
    - tmux
    - terraform
    - terraformer
    - ssm-session-manager-plugin
    - asdf-vm
    - adrgen
    - hasura-cli
    - google-cloud-sdk
    - copilot-cli
    - yadm
    - jq
    - wget
    - gnupg
    - alacritty
    - yadm
    - graphviz
    - dconf2nix
    - ruby_3_2
    - devbox
    - _1password-gui
    - docker
    - docker-compose
    - ripgrep
    - curl
    - unzip
    - tmux
    - localsend
    - hurl
    - discord
    - slack-dark
    - awscli2
    - nodejs_18
    - go
    - ngrok
    - conda
    - cloudflared
    - youtube-dl
    - yt-dlp
    - poetry
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - git
    - gh
    - helix
    - fish
shell: zsh
systems:
    - arch: aarch64
      home: ""
      hostname: macbook.local
      os: darwin
      user:
        email: rob@sharp.id.au
        name: Rob Sharp
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: qnm
      username: qnm
    - arch: x86_64
      home: ""
      hostname: fedora
      os: linux
      user:
        email: rob@sharp.id.au
        name: Rob Sharp
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: qnm
      username: qnm
    - arch: x86_64
      home: ""
      hostname: windoze
      os: linux
      user:
        email: rob@sharp.id.au
        name: Rob Sharp
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: qnm
      username: qnm
    - arch: aarch64
      home: ""
      hostname: robBook.local
      os: darwin
      user:
        email: rob@sharp.id.au
        name: Rob Sharp
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: qnm
      username: qnm
track: nixos-unstable
unfree: true
users: []
