name: Find Secrets
on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.78.2
